baseURL = "https://www.kenneth-mitchell.com/"
languageCode = "en-us"
title = "Kenneth Mitchell"
enableRobotsTXT = true

disableKinds = ["taxonomy", "term"]

[permalinks]
  posts = "/:slug/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    style = "github"
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[params]
